<Project Sdk="Godot.NET.Sdk/4.6.2">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<PlatformTarget>x64</PlatformTarget>
		<GodotPath>"D:\Godot_v4.6.2-stable_mono_win64\Godot_v4.6.2-stable_mono_win64_console.exe"</GodotPath>
		<Sts2Path>E:\SteamLibrary\steamapps\common\Slay the Spire 2</Sts2Path>
		<!-- Disable C# source generators to avoid type conflicts with referenced assemblies -->
		<EnableSourceGenerators>false</EnableSourceGenerators>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="0.1.9" />
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>$(Sts2Path)\data_sts2_windows_x86_64\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="sts2">
			<HintPath>$(Sts2Path)\data_sts2_windows_x86_64\sts2.dll</HintPath>
			<Publicize>True</Publicize>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Core\" />
		<Folder Include="Network\Messages\" />
		<Folder Include="Network\" />
		<Folder Include="Ui\" />
		<Folder Include="Integration\" />
	</ItemGroup>

	<Target Name="EnsureModsDirectory" BeforeTargets="PostBuildEvent">
		<MakeDir Directories="$(Sts2Path)\mods" />
	</Target>

	<Target Name="CopyAssemblyToMods" AfterTargets="PostBuildEvent">
		<Message Text="Copying .dll to mods folder." Importance="high" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(Sts2Path)\mods\" />
	</Target>

	<Target Name="GodotPublish" AfterTargets="Publish">
		<Message Text="Exporting Godot .pck to mods folder..." Importance="high" />
		<Exec Command="start &quot;Godot Export&quot; /wait $(GodotPath) --headless --export-pack &quot;Windows Desktop&quot; &quot;$(Sts2Path)\mods\$(MSBuildProjectName).pck&quot;" ContinueOnError="WarnAndContinue" />
	</Target>
</Project>